### ISSUE TITLE
Callback URL is coming empty for some customers

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/magento2-plugin#1]
- This is being reported persistently (probably a cache issues)
- A simple fix is to add a text in the settings to refresh cache  is callback URL is empty

https://screenshots.firefox.com/sVNG3q3V1UpYQ6ne/mail.google.com
https://static.livechatinc.com/5701831/P8PNA6XDYU/3341ee2e623087196db21cb16f6d5b00/btcpay.jpg

**Comment by jusasiiv** [comment]
Done in: https://github.com/blockonomics/magento2-plugin/commit/3fe26331daeef18d625ace55a3fbe29a4030b8f6
