### ISSUE TITLE
Error on expiry page

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/magento2-plugin#16]
https://cdn.livechat-static.com/api/file/v2/lc/att-old/5701831/539f95cecbfd74b0c15a6c6725376be4/timeout-error-1.png

Also reported by another merchant on telegram

**Comment by DarrenWestwood** [comment]
Fixed with https://github.com/blockonomics/magento2-plugin/pull/14

**Comment by jusasiiv** [comment]
Verified to fix issue, screenshots of fixed states:
![Screenshot_2019-10-08 Screenshot](https://user-images.githubusercontent.com/33265060/66427788-63279380-ea1d-11e9-9582-a8614ea244b6.png)
![Screenshot_2019-10-08 Orders Operations Sales Magento Admin](https://user-images.githubusercontent.com/33265060/66427789-63279380-ea1d-11e9-9bae-38f12c1a3c60.png)
![Screenshot_2019-10-08 Order # 000000004](https://user-images.githubusercontent.com/33265060/66427791-63279380-ea1d-11e9-8531-451747fe3be6.png)
![Screenshot_2019-10-08 Orders Operations Sales Magento Admin(1)](https://user-images.githubusercontent.com/33265060/66427792-63279380-ea1d-11e9-9d02-f25642cbca37.png)
![Screenshot_2019-10-08 Order # 000000004(1)](https://user-images.githubusercontent.com/33265060/66427794-63c02a00-ea1d-11e9-9347-08a69414756c.png)
