### ISSUE TITLE
Allow administrator to adjust price +/

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/magento2-plugin#4]
Give setting option to change price by percentage +/- ... allow maximum 30% both sides

**Comment by jusasiiv** [comment]
Done, commits:
042a4d8cc0403b25d717cfa2b200a3c9fc8581f2
c1f4c2d484376661e19d98d1d1a4f0ae5896de7f
8c0771dd3616188152aa9720381edc59ad5d11ae
