### ISSUE TITLE
Paid order is always less than expected

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/magento2-plugin#5]
- Always compare [satoshis only](https://github.com/blockonomics/magento2-plugin/blob/master/view/adminhtml/templates/order/view/custom.phtml)
- Expected BTC Amount / Other fields are [not getting shown](https://cdn.livechat-static.com/api/file/v2/lc/att-old/5701831/1a19626531a5434aee482707d6a76fb7/2111111_Orders_Operations_Sales_Magento_Admin_-_2018-08-20_06.40.57.jpg)

**Comment by jusasiiv** [comment]
Fixed with e3b4c18d20bff675825b137cf5506117307ada7c
